EMPLOYEE <- read.csv("EMPLOYEE.txt")
EMPLOYEE_PHONE<- read.csv("EMPLOYEE_PHONE.txt")
INVOICES<- read.csv("INVOICES.txt")
PRODUCT<- read.csv("PRODUCT.txt")
SALES_ORDER<- read.csv("SALES_ORDER.txt")
SALES_ORDER_LINE<- read.csv("SALES_ORDER_LINE.txt")
STOCK_TOTAL<- read.csv("STOCK_TOTAL.txt")
DEPARTMENT<- read.csv("DEPARTMENT.txt")
CUSTOMER<- read.csv("CUSTOMER.txt")

#Make the databases
library(RSQLite) # RUN EVERY TIME
storedb<-dbConnect(RSQLite::SQLite(), "STORE-db.sqlite") # RUN EVERY TIME
dbWriteTable(storedb, "EMPLOYEE", EMPLOYEE)
dbWriteTable(storedb, "CUSTOMER", CUSTOMER, overwrite=TRUE)
dbWriteTable(storedb, "DEPARTMENT", DEPARTMENT)
dbWriteTable(storedb, "EMPLOYEE_PHONE", EMPLOYEE_PHONE)
dbWriteTable(storedb, "INVOICES", INVOICES,overwrite = TRUE)
dbWriteTable(storedb, "PRODUCT", PRODUCT)
dbWriteTable(storedb, "SALES_ORDER", SALES_ORDER,overwrite = TRUE)
dbWriteTable(storedb, "SALES_ORDER_LINE", SALES_ORDER_LINE,overwrite=TRUE)
dbWriteTable(storedb, "STOCK_TOTAL", STOCK_TOTAL,overwrite = TRUE)

dbListTables(storedb)

dbGetQuery(storedb, 'SELECT DISTINCT NAME FROM EMPLOYEE')
dbGetQuery(storedb, 'SELECT NAME FROM EMPLOYEE WHERE NAME LIKE "B%"')
dbGetQuery(storedb, 'SELECT AGE,NAME FROM EMPLOYEE WHERE NAME LIKE "%R%"')
dbGetQuery(storedb, 'SELECT NAME, NI_NO FROM EMPLOYEE')
dbGetQuery(storedb, 'SELECT * FROM EMPLOYEE WHERE AGE BETWEEN 31 AND 65')
dbGetQuery(storedb, 'SELECT COUNT(*) FROM SALES_ORDER')
dbGetQuery(storedb, 'SELECT DISTINCT COLOR FROM PRODUCT')
dbGetQuery(storedb, 'SELECT PROD_NO, SUM(QUANTITY) FROM SALES_ORDER_LINE GROUP BY PROD_NO')
dbGetQuery(storedb, 'SELECT PROD_NO, QUANTITY FROM SALES_ORDER_LINE WHERE QUANTITY<1000')

dbGetQuery(storedb, 'SELECT * FROM DEPARTMENT WHERE NAME NOT IN ("Stores")')
dbGetQuery(storedb, 'SELECT 2*QUANTITY FROM INVOICES')
dbGetQuery(storedb, 'SELECT SUM(QUANTITY) FROM INVOICES WHERE PROD_NO = "p1"')
dbGetQuery(storedb, 'SELECT DISTINCT ORDER_NO FROM SALES_ORDER_LINE WHERE QUANTITY <10000')
dbGetQuery(storedb, 'SELECT COLOR FROM PRODUCT ORDER BY COLOR DESC')

dbGetQuery(storedb, 'SELECT * FROM PRODUCT NATURAL JOIN SALES_ORDER_LINE')
dbGetQuery(storedb, 'SELECT * FROM SALES_ORDER_LINE')

dbGetQuery(storedb, 'SELECT * FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPT_NO=D.DEPT_NO')


dbGetQuery(storedb, 'SELECT DEPT_NO FROM EMPLOYEE WHERE EMP_NO IN (SELECT 
           EMP_NO FROM EMPLOYEE_PHONE E WHERE E.EXTENSION = "123")')

dbGetQuery(storedb, 'SELECT NAME,NI_NO FROM EMPLOYEE')

dbGetQuery(storedb, 'SELECT AGE FROM EMPLOYEE WHERE AGE>(SELECT MAX(AGE)
                    FROM EMPLOYEE WHERE DEPT_NO = "D1")')
NEWPRODUCT<-dbSendQuery(storedb,'INSERT INTO CUSTOMER VALUES ("C7","MICHAEL", "Mesa")')
dbReadTable(storedb,"CUSTOMER")

dbGetQuery(storedb,'SELECT PROD_NO, SUM(QUANTITY) FROM SALES_ORDER_LINE GROUP BY PROD_NO')

TOTAL_ORDERS<-dbGetQuery(storedb,'SELECT PROD_NO, SUM(QUANTITY) AS QUANTITY FROM SALES_ORDER_LINE GROUP BY PROD_NO')
dbWriteTable(storedb, "TOTAL_ORDERS", TOTAL_ORDERS, overwrite = TRUE)
TOTAL_ORDERS

dbGetQuery(storedb,'SELECT DISTINCT S.PROD_NO FROM TOTAL_ORDERS T, STOCK_TOTAL S WHERE T.QUANTITY>=S.QUANTITY AND T.PROD_NO= S.PROD_NO OR S.QUANTITY=0')

dbGetQuery(storedb,'SELECT DISTINCT C.NAME, P.NAME, P.COLOR FROM CUSTOMER C, SALES_ORDER S, PRODUCT P, SALES_ORDER_LINE O
WHERE (C.NAME = "ALEX" OR C.NAME = "CAROL") AND C.CUST_NO = S.CUST_NO AND S.ORDER_NO = O.ORDER_NO AND O.PROD_NO=P.PROD_NO')

dbRemoveTable(storedb,'CUSTOMER')
dbListTables(storedb)

dbGetQuery(storedb,'SELECT ORDER_NO, PROD_NO FROM PRODUCT NAUTRAL JOIN SALES_ORDER_LINE')





